name: Build and Push Docker image

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/teslo-shop:latest
          build-args: |
            MONGO_URL=${{ secrets.MONGO_URL }}
            HOST_NAME=${{ secrets.HOST_NAME }}
            NEXT_PUBLIC_PAYPAL_CLIENT_ID=${{ secrets.NEXT_PUBLIC_PAYPAL_CLIENT_ID }}
            PAYPAL_SECRET=${{ secrets.PAYPAL_SECRET }}
            PAYPAL_OAUTH_URL=${{ secrets.PAYPAL_OAUTH_URL }}
            PAYPAL_ORDERS_URL=${{ secrets.PAYPAL_ORDERS_URL }}
            ID_GITHUB=${{ secrets.ID_GITHUB }}
            SECRET_GITHUB=${{ secrets.SECRET_GITHUB }}
